### ISSUE TITLE
Migrating spring data mongo from 1.9.9 to 3.2.2  getiing run time time exception

### ISSUE THREAD

**Issue by KSandhyaDevi** [spring-projects/spring-data-mongodb#3911] opened 2021-12-10 07:53 UTC
getCredentials called....
Replica Set: <Mongo nodes ips>org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'currencyInfo' defined in URL : Invocation of init method failed; nested exception is com.mongodb.MongoTimeoutException: Timed out after 50000 ms while waiting for a server that matches com.mongodb.client.internal.MongoClientDelegate$1@4bc59b27. Client view of cluster state is {type=REPLICA_SET, servers=[]

I followed xml based mongo templete creation,
old :
<mongo:db-factory id="campaignsDBMongoDBFactory" mongo-ref="campaignsDBMongo" dbname="${campaignsDB.mongodb.db}"/>
    <mongo:repositories base-package="com.todo.campaignsdb.spring.nsfw.repositories" mongo-template-ref="campaignsDBMongoTemplate"/>

    <bean id="campaignsDBMongoTemplate" class="org.springframework.data.mongodb.core.MongoTemplate">
        <constructor-arg name="mongoDbFactory" ref="campaignsDBMongoDBFactory"/>
    </bean>

    <mongo:mongo-client replica-set="#{campaignsDBMongoConfig.replicaSet}"  id="campaignsDBMongo" credentials="#{campaignsDBMongoConfig.credentials}">
        <mongo:client-options min-connections-per-host="${campaignsDB.mongodb.minConnectionsPerHost}"
                              connections-per-host="${campaignsDB.mongodb.connectionsPerHost}"
                              connect-timeout="${campaignsDB.mongodb.connectTimeout}"
                              heartbeat-connect-timeout="${campaignsDB.mongodb.heartbeatConnectTimeout}"
                              heartbeat-frequency="${campaignsDB.mongodb.heartbeatFrequency}"
                              heartbeat-socket-timeout="${campaignsDB.mongodb.heartbeatSocketTimeout}"
                              max-connection-idle-time="${campaignsDB.mongodb.maxConnectionIdleTime}"
                              max-connection-life-time="${campaignsDB.mongodb.maxConnectionLifeTime}"
                              max-wait-time="${campaignsDB.mongodb.maxWaitTime}"
                              min-heartbeat-frequency="${campaignsDB.mongodb.minHeartbeatFrequency}"
                              socket-keep-alive="${campaignsDB.mongodb.socketKeepAlive}"
                              socket-timeout="${campaignsDB.mongodb.socketTimeout}"
        />
    </mongo:mongo-client>

new xml

<mongo:repositories base-package="com.todo.campaignsdb.spring.nsfw.repositories" mongo-template-ref="myOps" />
    
    <mongo:mongo-client replica-set="rs" id="campaignsDBMongo"  credential="#{campaignsDBMongoConfig.credentials}" >
		 <mongo:client-settings
		   cluster-hosts="#{campaignsDBMongoConfig.replicaSet}"
		   cluster-server-selection-timeout="${campaignsDB.mongodb.connectTimeout}"
		   connection-pool-min-size="${campaignsDB.mongodb.minConnectionsPerHost}"
		   connection-pool-max-size="${campaignsDB.mongodb.connectionsPerHost}"
		   connection-pool-max-wait-time="${campaignsDB.mongodb.maxWaitTime}"
		   connection-pool-max-connection-idle-time="${campaignsDB.mongodb.maxConnectionIdleTime}"
	   	   connection-pool-max-connection-life-time="${campaignsDB.mongodb.maxConnectionLifeTime}"
		   server-heartbeat-frequency="${campaignsDB.mongodb.heartbeatFrequency}"
		   server-min-heartbeat-frequency="${campaignsDB.mongodb.minHeartbeatFrequency}"
		   socket-connect-timeout="${campaignsDB.mongodb.socketTimeout}"
		 />
	</mongo:mongo-client>
    
  	<mongo:db-factory id="campaignsDBMongoDBFactory" mongo-client-ref="campaignsDBMongo" dbname="${campaignsDB.mongodb.db}"/>
  	
  	<bean id="campaignsDBMongoTemplate" class="org.springframework.data.mongodb.core.MongoTemplate">
        <constructor-arg name="mongoDbFactory" ref="campaignsDBMongoDBFactory"/>
    </bean>
    

--------------
campaignsDBMongoConfig.credentials}

old value : 
this.credentials = this.userName + ":" + dbPwd + "@" + this.authDb;

new value:
this.credentials = MongoCredential.createCredential(this.userName,dbPwd,ch);

**Comment by KSandhyaDevi** [comment] 2021-12-10 07:54
Can you please help me with correct approach of xml creation

**Comment by KSandhyaDevi** [comment] 2021-12-15 04:56
Hi Team,

Please help me with this. This is very important change for my project. Can you please provide details.

**Comment by christophstrobl** [comment] 2021-12-15 08:21
Moving from _1.x_ to _3.x_ is quite a change that involves config, client and other differences. With the information at hand we cannot tell why the client won't connect to the replica set. Maybe you could set up the client manually with the required settings to see which ones are not set the expected way using XML config.

**Comment by KSandhyaDevi** [comment] 2021-12-16 05:19
Hi Christophstobl,
When I got the info from spring docs i changed to new xml version changes, 
I googled it alot, But I didn't find any xml type of config in 3.x version of spring data mongo. Can you please provide any sample application with xml based in 3.x.

**Comment by KSandhyaDevi** [comment] 2021-12-16 05:47
Hi Christophstobl,
As our company using mongo huge. We are doding millions of transactions in milliseconds on mongo. so we need best way of connecting multiple mongos in multiple applications and we have replica sets also.

**Comment by christophstrobl** [comment] 2021-12-16 07:28
With the given information I was not able to reproduce the issue. The mentioned authentication changes should not lead to a server selection timeout but raise a `MongoSecurityException`. My best guess (based on the information you provided `type=REPLICA_SET, servers=[]`) is something related to `clusterHosts`.
Please try debugging your application. Breakpoints in `MongoParsingUtils` and `MongoClientFactoryBean` might help you.

**Comment by spring-projects-issues** [comment] 2021-12-24 08:17
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-projects-issues** [comment] 2022-01-04 09:57
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-projects-issues** 2022-01-04 09:57 UTC
Labels: status: waiting-for-feedback, status: feedback-reminder
