### ISSUE TITLE
`@DocumentReference` does not work as a drop-in replacement of `@DBRef`

### ISSUE THREAD

**Issue by ntf** [spring-projects/spring-data-mongodb#3792] opened 2021-08-30 16:33 UTC
Hi there,

I came across the new feature `@DocumentReference` as I was working on something that needs support of another new feature `TimeSeries` .

I was trying to use `@DocumentReference` on a new field as I want to store `["612cf1ef637b391363f1392e"]` instead of the DbRef equivalent `["{ \"$ref\" : \"COLLECTION_NAME\", \"$id\" : \"612cf1ef637b391363f1392e\" }"]`

Following the documentation here: https://docs.spring.io/spring-data/mongodb/docs/3.3.0-M2/reference/html/#mapping-usage.document-references

I thought I could use (Kotlin)
```kotlin
@DocumentReference(collection = "COLLECTION_NAME", lookup = "{ '_id' : ?#{#target} }")
var myList: List<MyListItem> = mutableListOf()
```
 as a drop-in replacement of 
```java
@DBRef
```
But unfortunately it doesn't work as I expected.

I tried both `MongoRepository` and `MongoTemplate`  and both complain about missing a converter from a `String` to `MyListItem`.

With the help of a debugger, I think it should be related to this block of code. 

https://github.com/spring-projects/spring-data-mongodb/blob/3.3.0-M2/spring-data-mongodb/src/main/java/org/springframework/data/mongodb/core/convert/MappingMongoConverter.java#L2068

I was expecting there is a block of code similar to the `DbRef` that help resolving `DocumentReference`.
```java
if (source instanceof DBRef) {
    return (S) dbRefConverter.convert(this, (DBRef) source, typeHint);
}
```

**Comment by christophstrobl** [comment] 2021-08-31 07:38
From reading the description I cannot spot what exactly the issue might be, given that tests in `MongoTemplateDocumentReferenceTests` should cover this pass.
Do you have a [minimal sample](https://stackoverflow.com/help/minimal-reproducible-example) (something that we can unzip or git clone, build, and deploy) that reproduces the problem? This would help us identify the issue.

**Comment by ntf** [comment] 2021-08-31 08:58
I crafted this example just now with Spring Initializr.

[test-mongo-documentreference.zip](https://github.com/spring-projects/spring-data-mongodb/files/7082546/test-mongo-documentreference.zip)

Attached belo MongoDb datatabase view on Intellij IDEA.
![image](https://user-images.githubusercontent.com/355340/131472881-2b4796c0-8b7b-4efe-96ec-6c3185fd7949.png)

> Caused by: org.springframework.core.convert.ConverterNotFoundException: No converter found capable of converting from type [java.lang.String] to type [com.example.demo.models.Instrument]
	at org.springframework.core.convert.support.GenericConversionService.handleConverterNotFound(GenericConversionService.java:322) ~[spring-core-5.3.9.jar:5.3.9]
	at org.springframework.core.convert.support.GenericConversionService.convert(GenericConversionService.java:195) ~[spring-core-5.3.9.jar:5.3.9]
	at org.springframework.core.convert.support.GenericConversionService.convert(GenericConversionService.java:175) ~[spring-core-5.3.9.jar:5.3.9]
	at org.springframework.data.mongodb.core.convert.MappingMongoConverter.doConvert(MappingMongoConverter.java:1679) ~[spring-data-mongodb-3.3.0-M2.jar:3.3.0-M2]
	at org.springframework.data.mongodb.core.convert.MappingMongoConverter.doConvert(MappingMongoConverter.java:1671) ~[spring-data-mongodb-3.3.0-M2.jar:3.3.0-M2]
	at org.springframework.data.mongodb.core.convert.MappingMongoConverter.getPotentiallyConvertedSimpleRead(MappingMongoConverter.java:1192) ~[spring-data-mongodb-3.3.0-M2.jar:3.3.0-M2]
	at org.springframework.data.mongodb.core.convert.MappingMongoConverter.getPotentiallyConvertedSimpleRead(MappingMongoConverter.java:1166) ~[spring-data-mongodb-3.3.0-M2.jar:3.3.0-M2]
	at org.springframework.data.mongodb.core.convert.MappingMongoConverter$ConversionContext.convert(MappingMongoConverter.java:2068) ~[spring-data-mongodb-3.3.0-M2.jar:3.3.0-M2]
	at org.springframework.data.mongodb.core.convert.MappingMongoConverter.readCollectionOrArray(MappingMongoConverter.java:1276) ~[spring-data-mongodb-3.3.0-M2.jar:3.3.0-M2]
	at org.springframework.data.mongodb.core.convert.MappingMongoConverter$ConversionContext.convert(MappingMongoConverter.java:2038) ~[spring-data-mongodb-3.3.0-M2.jar:3.3.0-M2]
.....
	at com.example.demo.DemoApplication.run(DemoApplication.kt:36) ~[main/:na]

**Comment by christophstrobl** [comment] 2021-09-28 09:18
Thanks for the sample. There's been an update on constructor argument handling in the recent `M3` release that fixes parameter conversion. However the sample reveals another issue in expression evaluation that needs to be targeted before RC1.

**Comment by ntf** [comment] 2021-09-28 18:02
You are welcome and glad this helps.

**Comment by christophstrobl** [comment] 2021-11-11 14:55
I think we can close this one because #3842 has been resolved meanwhile. If you're still having trouble please feel free to drop a note and reopen the issue.

**Closed by christophstrobl** 2021-11-11 14:55 UTC
Labels: status: feedback-provided, in: references

**Comment by ntf** [comment] 2021-11-11 18:08
Thanks @christophstrobl , although I don't understand how the change set in #3842 fixed this issue but I will take some time to upgrade and revert if it doesn't fix the issue.
