### ISSUE TITLE
use mongoTemplate.find but create index and wrong finally

### ISSUE THREAD

**Issue by LiuxuyangK** [spring-projects/spring-data-mongodb#3564] opened 2021-02-19 07:11 UTC
error message is:Index with pattern: 

The full response is { "ok" : 0.0, "errmsg" : "Index with pattern: { pric_key: 1 } already exists with different options", "code" : 85 }

we use   @Indexed(unique = true) to create Index。

  @Indexed(unique = true)
    @Field(value = "pric_key")
    private String pricKey;

**Comment by christophstrobl** [comment] 2021-02-19 07:35
The message indicates that the specified index already exists. A bit more context would help us triage the issue.
Did you change the index configuration (eg. by adding the `unique` flag)? Is there more than one domain type persisted in the same collection?  Which version are you using? 
Maybe you can provide a [Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example).

**Comment by spring-projects-issues** [comment] 2021-02-26 07:37
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-projects-issues** [comment] 2021-03-05 07:38
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-projects-issues** 2021-03-05 07:38 UTC
Labels: status: feedback-reminder, status: waiting-for-feedback
