### ISSUE TITLE
@Sharded annotation not adding shard key to query filter 

### ISSUE THREAD

**Issue by RohitShete99** [spring-projects/spring-data-mongodb#3955] opened 2022-02-08 11:41 UTC
As per documentation
 **update/upsert operations replacing/upserting a single existing document as long as the given [UpdateDefinition](https://docs.spring.io/spring-data/mongodb/docs/current/api/org/springframework/data/mongodb/core/query/UpdateDefinition.html) holds a full copy of the entity.**
 
 I have DataDTO with 13 fields out of which 6 fields are transient, DataDTO is extending CommonDTO which has 8 fields. DataDTO(Data) collection is sharded with shard key name, I have added @Sharded annotation like below and I am setting all non transient 15 fields in updateDefinition still the upsert is getting failed with could not extract exact shard key error 
 
 
 I am hitting upsert with this.mongoTemplate.upsert(query, update, DataDTO.class) where query has equality filter on other field address (address="XYZ") with upsert:true & multi:false
 
 Details:
 MongoDB java driver 4.4.0 sync+core
 MongoDB server 4.2.5
 Spring data mongodb 3.3.0
 Spring boot 2.6.2 
 
@Document(collection = "Data")
public class DataDTO extends CommonDTO

@Document
@Sharded(shardKey = { "name"}) 
public class CommonDTO
{
	@Field("name")
	private String name;
	
	....other 7 fields

}
As per @Sharded annotation I am adding all the fields in updateDefinition i.e. full copy of entity is present in updateDefinition still it is throwing error
 Write error: WriteError{code=61, message='Failed to target upsert by query :: could not extract exact shard key'

**Comment by christophstrobl** [comment] 2022-02-08 11:58
Can you please add a sample that shows the update itself. Ideally take the time to provide a complete [minimal sample](https://stackoverflow.com/help/minimal-reproducible-example) (something that we can unzip or git clone, build, and deploy) that reproduces the problem.

**Comment by RohitShete99** [comment] 2022-02-08 12:03
It is difficult to provide complete minimal sample for the same, What will be the ideal way to use @Sharded annotation

**Comment by spring-projects-issues** [comment] 2022-02-21 14:55
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-projects-issues** [comment] 2022-02-28 14:55
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-projects-issues** 2022-02-28 14:55 UTC
Labels: status: waiting-for-feedback, status: waiting-for-triage, status: feedback-reminder
