### ISSUE TITLE
RejectedExecutionException when using  spring-data-mongodb 

### ISSUE THREAD

**Issue by ningbingjian1** [spring-projects/spring-data-mongodb#4583] opened 2023-12-07 10:43 UTC
Dear friends,
On our project we faced with issue when using spring-data-mongodb cause RejectedExecutionException.

my project is springboot project .

Here are some code snippets:

App.java
```
package org.example;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.scheduling.annotation.EnableAsync;
import org.springframework.scheduling.annotation.EnableScheduling;
@SpringBootApplication
@EnableScheduling
@EnableAsync
public class App 
{
    public static void main( String[] args )
    {
        SpringApplication.run(App.class, args);
    }
}
```

application.yml
```
server:
  port: ${PORT:9091}
spring:
  data:
    mongodb:
      uri: mongodb://user:pwd@ip1:3717,ip2:3717/test
```
pom.xml
```
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <parent>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-parent</artifactId>
    <version>2.6.6</version>
    <relativePath/>
  </parent>


  <groupId>org.example</groupId>
  <artifactId>mongodb-spring-test</artifactId>
  <version>1.0-SNAPSHOT</version>
  <packaging>jar</packaging>

  <name>mongodb-spring-test</name>
  <url>http://maven.apache.org</url>

  <properties>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
  </properties>

  <dependencies>
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-data-mongodb</artifactId>
    </dependency>

    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-web</artifactId>
    </dependency>

  </dependencies>
</project>

```

when run App.java ,we got and exception .

```
Exception in thread "cluster-ClusterId{value='65719cfd38fa7c5f1371f08f', description='null'}-dds-ip:3717" java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@6d58ac99[Not completed, task = java.util.concurrent.Executors$RunnableAdapter@4e3a134c[Wrapped task = com.mongodb.internal.connection.DefaultConnectionPool$BackgroundMaintenanceManager$$Lambda$812/0x0000000900550440@50081cf2]] rejected from java.util.concurrent.ScheduledThreadPoolExecutor@789c5e0e[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 0]
	at java.base/java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2055)
	at java.base/java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:825)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(ScheduledThreadPoolExecutor.java:340)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor.scheduleAtFixedRate(ScheduledThreadPoolExecutor.java:632)
	at java.base/java.util.concurrent.Executors$DelegatedScheduledExecutorService.scheduleAtFixedRate(Executors.java:785)
	at com.mongodb.internal.connection.DefaultConnectionPool$BackgroundMaintenanceManager.start(DefaultConnectionPool.java:1419)
	at com.mongodb.internal.connection.DefaultConnectionPool$StateAndGeneration.ready(DefaultConnectionPool.java:1500)
	at com.mongodb.internal.connection.DefaultConnectionPool.ready(DefaultConnectionPool.java:270)
	at com.mongodb.internal.connection.DefaultSdamServerDescriptionManager.lambda$update$0(DefaultSdamServerDescriptionManager.java:72)
	at com.mongodb.internal.connection.BaseCluster.withLock(BaseCluster.java:271)
	at com.mongodb.internal.connection.AbstractMultiServerCluster.withLock(AbstractMultiServerCluster.java:50)
	at com.mongodb.internal.connection.DefaultSdamServerDescriptionManager.update(DefaultSdamServerDescriptionManager.java:60)
	at com.mongodb.internal.connection.DefaultServerMonitor$ServerMonitorRunnable.run(DefaultServerMonitor.java:165)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

This error occurs after startup, not every time, but with a high probability

Can someone help me with this? Please

**Comment by christophstrobl** [comment] 2023-12-07 10:58
This looks like an internal driver issue (similar to [JAVA-4551](https://jira.mongodb.org/browse/JAVA-4551)), though it's hard to tell if it's somehow related to the async/scheduled bits of the app. 
If you'd like us to spend some time investigating, please take the time to provide a complete [minimal sample](https://stackoverflow.com/help/minimal-reproducible-example) (something that we can unzip or git clone, build, and deploy) that reproduces the problem.

**Comment by christophstrobl** [comment] 2023-12-10 15:30
Thanks @ningbingjian1 - I'll give the sample a try and see if I can reproduce locally.

**Comment by christophstrobl** [comment] 2023-12-12 13:10
Running the provided sample, there seems to be nothing unusual. Please mind that the used version of Spring Boot (2.6.x) and data-mongodb (3.3.x) is out of support since the end of 2022 already.
Unless there's more information I'm inclined to close this issue.

**Comment by ningbingjian1** [comment] 2023-12-25 06:19
> This looks like an internal driver issue (similar to [JAVA-4551](https://jira.mongodb.org/browse/JAVA-4551)), though it's hard to tell if it's somehow related to the async/scheduled bits of the app. If you'd like us to spend some time investigating, please take the time to provide a complete [minimal sample](https://stackoverflow.com/help/minimal-reproducible-example) (something that we can unzip or git clone, build, and deploy) that reproduces the problem.



This will solve my problem, I just need to upgrade the version.

**Comment by christophstrobl** [comment] 2024-01-08 07:24
@ningbingjian1 thanks for letting us know. Closing this one.

**Closed by christophstrobl** 2024-01-08 07:24 UTC
Labels: for: external-project, status: invalid
