### ISSUE TITLE
"Required identifier property not found" in Kotlin

### ISSUE THREAD

**Issue by shanedonburke** [spring-projects/spring-data-mongodb#3685] opened 2021-06-24 20:13 UTC
Hi,

I have a Kotlin project with `spring-boot-starter-data-mongodb-reactive`. My sealed class `Question` has a collection. Inserting and deleting work fine, but using my method for updating a document results in this:
```
"timestamp": 1624474446743,
    "path": "/api/questions/60d3834eef43b774dbb458d5",
    "status": 500,
    "error": "Internal Server Error",
    "message": "Required identifier property not found for class com.sdbtechnology.surveytool.assessment.Question!",
    "requestId": "b8726976-6",
    "trace": "java.lang.IllegalStateException: Required identifier property not found for class com.sdbtechnology.surveytool.assessment.Question!
``` 
`Question.kt` looks like this:
```kotlin
@JsonIgnoreProperties(ignoreUnknown = true)
@Document(collection = QuestionRepository.COLLECTION_NAME)
sealed class Question : Scorable {
  abstract var id: String?
  // ...
  @Document(collection = QuestionRepository.COLLECTION_NAME)
  data class Text(
    override var id: String? = null,
    override val name: String? = null,
    override val tags: MutableSet<String>? = null,
    override val bodyComponents: List<BodyContent>,
    override val required: Boolean,
    val pattern: String? = null,
    val tag: TextQuestionTag = TextQuestionTag.NONE,
    override val correctTextAnswers: List<String>? = null
  ) : Question(), SimpleTextBased {
      // ...
```
I'm updating the document with this code:
```kotlin
open class BaseRepositoryImpl<T : Any, ID : Serializable>(
    private val entityInformation: MongoEntityInformation<T, ID>,
    private val mongoOperations: ReactiveMongoOperations
) : SimpleReactiveMongoRepository<T, ID>(entityInformation, mongoOperations), BaseRepository<T, ID> {
    override fun <S : T> update(entity: S): Mono<S> {
        val id = entityInformation.idAttribute
        val entityId = entityInformation.getRequiredId(entity)
        return mongoOperations.findAndReplace(
            Query(where(id).isEqualTo(entityId)),
            entity,
            options().returnNew(),
            entityInformation.collectionName
        ).switchIfEmpty(
            Mono.error(RuntimeException("Entity [${entityInformation.javaType.name} $entityId] not found"))
        )
    }
}
```
Specifically, the call to `entityInformation.idAttribute` is failing. It works fine for my other (non-abstract) document class.

I've tried the following things:
1. Making sure `id` isn't null
2. Annotating `id` with `@Id` in both `Question` and `Text`
3. Doing the same with `@MongoId`
4. Making `id` not abstract
5. Changing the type of `id` to `ObjectId` instead of `String`

Is there anything obviously wrong here? Thanks

**Comment by christophstrobl** [comment] 2021-06-25 06:04
Thanks for reporting. Which version of data-mongodb are you using?
We've seen `override` cause trouble when trying to resolve properties, so this might be related to spring-projects/spring-data-commons#1911. So you might want to give current main line snapshot builds a try, because the fix for the above mentioned issue has not yet seen a release.
Also a [minimal sample](https://stackoverflow.com/help/minimal-reproducible-example) (something that we can unzip or git clone, build, and deploy) that reproduces the problem would help us reproduce the problem.

**Comment by shanedonburke** [comment] 2021-06-25 14:19
Thanks for the quick response. I'm using `2.2.6.RELEASE`.

**Comment by christophstrobl** [comment] 2022-01-19 12:34
The fix for spring-projects/spring-data-commons#1911 has been released and is available via `3.3.0`. Does the issue still exist when using that version?

**Comment by spring-projects-issues** [comment] 2022-01-26 12:37
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-projects-issues** [comment] 2022-02-02 12:37
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-projects-issues** 2022-02-02 12:37 UTC
Labels: status: feedback-reminder
