### ISSUE TITLE
ReactiveMongoTemplate.changeStream ignores FullDocumentBeforeChange option passed with argument ChangeStreamOptions

### ISSUE THREAD

**Issue by gautampushpa2008** [spring-projects/spring-data-mongodb#4539] opened 2023-10-27 15:36 UTC
Hello Team,

Recently working on the SpringBoot Reactive change stream API, I found that the ReactiveMongoTemplate.changeStream method doesn't consider the FullDocumentBeforeChange option passed along with the argument ChangeStreamOptions, and the publisher i.e., ChangeStreamPublisherImpl always use the FullDocumentBeforeChange.DEFAULT option while watching the change events on a collection. Due to this, I am unable to retrieve the preimage of a collection from the MongoDB and the value for field fullDocumentBeforeChange is always null in the ChangeStreamEvent. Could you please provide a solution for this?

Spring boot version: 3.1.0/3.1.5
Dependency: org.springframework.boot:spring-boot-starter-data-mongodb-reactive

**Comment by christophstrobl** [comment] 2023-11-02 05:43
Thanks for the report - this seems to be a duplicate of #4495 which needs to be fixed.

**Closed by christophstrobl** 2023-11-02 05:43 UTC
Labels: status: waiting-for-triage
