### ISSUE TITLE
How to perform an Upsert on a bulk with Reactive Streams?

### ISSUE THREAD

**Issue by apffa** [spring-projects/spring-data-mongodb#3994] opened 2022-03-15 11:27 UTC
As for what I've seen, the `ReactiveMongoTemplate` doesn't support a [multi update when upserting](https://github.com/spring-projects/spring-data-mongodb/blob/391d5101d80d3b9a7bbf512f5e1a779f4730fc25/spring-data-mongodb/src/main/java/org/springframework/data/mongodb/core/ReactiveMongoTemplate.java#L1802). I wonder if there's any reason for this, or whether it will be possible to submit a simple PR to fix that.

**Comment by apffa** [comment] 2022-03-15 15:06
@mp911de

**Comment by almogtavor** [comment] 2022-03-16 18:36
There's a non-Spring Data implementation [specified here](https://stackoverflow.com/questions/70926335/bulk-update-with-spring-data-mongodb-reactive). I think there is no reason to not simplify this in Spring Data Mongo. Bulk operations should be supported in `spring-data-mongo-reactive`

**Comment by christophstrobl** [comment] 2022-03-17 12:57
seem to be a duplicate of #2821 - a PR is always welcome.

**Comment by almogtavor** [comment] 2022-03-19 16:51
@christophstrobl Ok. Can you specify what path should the `ReactiveBulkOperations` interface be? I guess the implementation should be in a class named `ReactiveBulkOperationsSupport`. If you may, some guidelines for what needed to be implemented.

**Comment by mp911de** [comment] 2022-04-06 12:35
Both, the implementation and interface should reside in the `core` (`org.springframework.data.mongodb.core`) package. Closing this one as duplicate of #2821.

**Closed by mp911de** 2022-04-06 12:35 UTC
Labels: status: duplicate
