### ISSUE TITLE
[Enhance] Expose function wich translate ObjectID to hexId.

### ISSUE THREAD

**Issue by c0ncentus** [spring-projects/spring-data-mongodb#3845] opened 2021-09-28 20:13 UTC
hi, 

Spring boot : 2.5.4
Java : 16

## What
Please expose a function for translating this:
```
  "_id": {
    "timestamp": 1632668571,
    "date": "2021-09-26T15:02:51.000+00:00"
  },
```
to 

![image](https://user-images.githubusercontent.com/25374826/135146421-3cf95b1d-ae08-4d45-a320-52c6a8376001.png)

## Why
I understand that Spring boot expose many annotations.
 However I want my API  **binding** my mongodb database with my endpoints.

So I can build my Springboot mainly with JSONObject, Document and ObjectMapper.

I don't want any mapping class(I Have my reasons). 
I not saying there is no advandage to make classes on Spring Boot but I have reasons and context.

PS: in Spring Java Mongo  (.find or .iterable or maybe .into(new ArrayList<Document>))
Some access methods return me 
 => { "_id":{$oid:"hexa"}} (good one) 
and others 
=> {"_id":{date:"", timestamp:100000}}* (bad one) 

i want a function to pick up **_the string hex_** **either with** $oid **either with** {date, timestamp}. 
I search it on the doc, I don't find it so far *.
Please make spring-data-mongodb easier to use.

**Comment by christophstrobl** [comment] 2021-09-29 06:00
Judging from what I understand given the description above, this does not seem to be related to Spring Data nor Spring Boot. 
For problems with the driver and/or the `bson.codecs` please reach out to the [team at MongoDB](https://jira.mongodb.org/projects/JAVA/).

In case this really is an issue Spring Data MongoDB, please spend some more time describing it. Ideally take the time to provide a complete [minimal sample](https://stackoverflow.com/help/minimal-reproducible-example) (something that we can unzip or git clone, build, and deploy) that reproduces the problem.

**Comment by c0ncentus** [comment] 2021-09-29 10:13
https://github.com/c0ncentus/Spring-mongo-issueId
PS: VerifyBeforEachRequest verify it's matching my config on Database config.
_
_
_
_
_
_
This is my only GET method (for fetch all data, such a real basic method for API)
"project" is Database and "object" is Collection
``` Java
	@RequestMapping(value = "/{project}/{object}", method = RequestMethod.GET, produces = MediaType.APPLICATION_JSON_VALUE)
	@ResponseBody
	@CrossOrigin
	public ResponseEntity<?> getAllUni(@RequestHeader Map<String, String> headers, @PathVariable String project,
			@PathVariable String object) {
		if (verifyBeforeEachRequest(headers, project, object, MethodHttp.GET_ALL.toString())) {

			MongoCollection<Document> col = DatabaseSupport.gotCollection(project, object);
			MongoCursor<Document> data = col.find().iterator();
			List<Document> arrayDoc = new ArrayList<Document>();
			while (data.hasNext()) {
				arrayDoc.add(data.next());
			}
			return ResponseEntity.ok(arrayDoc);

		} else {
			return ResponseEntity.badRequest().body("");
		}
	}
```

## Main issue I have
and have this type of data : 
```Json
[ 
    {
        "_id": {
                     "timestamp": 1632668571,
                     "date": "2021-09-26T15:02:51.000+00:00"
                },
          ...
     }
]
```
I expect to have this kind of data ... either this : 
```Json
[ 
    {
        "_id": {
                     "???":{ "hexaString"}
                },
          ...
     }
]
```
or either this (mongoose achieve this and I believe that is better because that's an id ...)
```Json
[ 
    {
        "_id": "hexaString",
          ...
     }
]
```



## Related to the post
I suppose mongo spring will not change, so I only ask for a function (not annotation)
that translate this
```Json
[ 
    {
        "_id": {
                     "timestamp": 1632668571,
                     "date": "2021-09-26T15:02:51.000+00:00"
                },
          ...
     }
]
```


to  


```Json
[ 
    {
        "_id": "hexaString",
          ...
     }
]
```

else my better solution is to create myself an id ... 

Do you want more details ?

**Comment by christophstrobl** [comment] 2021-09-29 12:08
I cannot see any usage of spring-data other than being referenced in the pom to have client configuration bootstrapped.
Closing this one because all interaction with MongoDB is done via custom code, unrelated to functionality spring data provides.

**Closed by christophstrobl** 2021-09-29 12:08 UTC
Labels: status: feedback-provided

**Comment by c0ncentus** [comment] 2021-09-29 13:17
extract from DatabaseSupport.java in nameOfFolder/src/main/java/com/feanaro/lindale_api    
if you talk about  spring-data-mongodb there it is some usage
``` 
import com.mongodb.client.MongoClients;
import com.mongodb.client.MongoClient;
import com.mongodb.client.result.DeleteResult;
import com.mongodb.client.result.InsertOneResult;
import com.mongodb.client.result.UpdateResult;
import com.mongodb.client.result.InsertManyResult;
import com.mongodb.client.MongoCursor;
import com.mongodb.client.MongoCollection;
import com.mongodb.client.FindIterable; 


public static MongoCollection<Document> gotCollection(String db, String col) {
        return getInstance().getDatabase(db).getCollection(col);
    }

```

are you sure ?

**Comment by christophstrobl** [comment] 2021-09-29 14:38
yes.
