### ISSUE TITLE
Add support for $getField aggregation operator.

### ISSUE THREAD

**Issue by christophstrobl** [spring-projects/spring-data-mongodb#4072] opened 2022-06-02 06:10 UTC
Since: MongoDB 5.0
See: https://www.mongodb.com/docs/manual/reference/operator/aggregation/getField/

**Comment by sxhinzvc** [comment] 2023-07-12 12:48
closing since it's a duplicate of https://github.com/spring-projects/spring-data-mongodb/issues/4139

**Comment by sxhinzvc** [comment] 2023-07-12 12:50
closing since it's a duplicate of https://github.com/spring-projects/spring-data-mongodb/issues/4139

**Closed** 2023-07-12 12:51 UTC
Labels: status: duplicate
