### ISSUE TITLE
Spring Boot 2 MongoDB @TypeAlias does not work [DATAMONGO-2466]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-mongodb#3321] opened 2020-02-08 21:57 UTC
**[Markus](https://jira.spring.io/secure/ViewProfile.jspa?name=mawasource)** opened **[DATAMONGO-2466](https://jira.spring.io/browse/DATAMONGO-2466?redirect=false)** and commented

In SpringBoot 1 TypeAlias("name") does work as expected but if I migrate to SpringBoot 2 it doesn't instantiate the classes correctly.

```java
@Document(collection = "test")
@TypeAlias("y")
public class TestY extends Test {

private String y;

public String getY() {
 return y;
 }

public void setY(String y) {
 this.y = y;
 }
}
```

```java
@Document(collection = "test")
public class Test {
 @Id
 protected String id;

public Test() {
 this.id = id;
 }
}
```

```java
@Document(collection = "test")
@TypeAlias("x")
public class TestX extends Test {

private String x;

public String getX() {
 return x;
 }

public void setX(String x) {
 this.x = x;
 }
}

```

**Executions:**

If I only load the instances -> Test instances should be TestX or TestY but they are all Test

```java
List<Test> test = testRepository.findAll(); 
```

If I save before the entities -> Test instances after loading are instantiated right as TestX and TestY

```java
 TestY y = new TestY();
 y.setY("y");
 testRepository.save(y);

TestX x = new TestX();
 x.setX("x");
 testRepository.save(x);
 List<Test> test = testRepository.findAll();
```

In Spring Boot 1 it works as expected.

**Dependencies**

before: spring-boot-starter-data-mongodb-1.5.21.RELEASE

after: spring-boot-starter-data-mongodb-2.1.11.RELEASE

**Repositories**

```java
@Repository
public interface TestRepository extends MongoRepository<Test, String> {

}
```

---

**Affects:** 2.1.16 (Lovelace SR16)

1 votes, 2 watchers

**Comment by Frejl** [comment] 2021-01-29 06:06
same issue for me

**Comment by legas1** [comment] 2021-05-22 21:49
Hi @mp911de ,

looks like I stepped upon this issue too after upgrading from Spring 2.3.2 -> 2.4.5 on my Kotlin project.

code bits:
```kotlin
sealed class Vehicle

@TypeAlias("bigVehicle")
data class BigVehicle(
    @Field("weight")
    val weight: Integer
) : Vehicle()

@Document(collection = "vehicleOrder")
data class VehicleOrder(
    @Field("vehicles")
    val vehicles: List<Vehicle> = listOf()
)
```

error:
```
org.springframework.data.mapping.model.MappingInstantiationException: Failed to instantiate com.example.Vehicle using constructor fun <init>(): com.example.VehicleOrder with arguments
        at org.springframework.data.mapping.model.ReflectionEntityInstantiator.createInstance(ReflectionEntityInstantiator.java:79)
        Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException:
Assembly trace from producer [reactor.core.publisher.FluxConcatMap] :
        reactor.core.publisher.Flux.concatMap(Flux.java:3635)
...
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.example.Vehicle]: Is it an abstract class?; nested exception is java.lang.InstantiationException
        at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:216)
        at org.springframework.data.mapping.model.ReflectionEntityInstantiator.createInstance(ReflectionEntityInstantiator.java:77)
        at org.springframework.data.mapping.model.ClassGeneratingEntityInstantiator.createInstance(ClassGeneratingEntityInstantiator.java:87)
        at org.springframework.data.mongodb.core.convert.MappingMongoConverter.read(MappingMongoConverter.java:348)
        at org.springframework.data.mongodb.core.convert.MappingMongoConverter.read(MappingMongoConverter.java:321)
        at org.springframework.data.mongodb.core.convert.MappingMongoConverter.readCollectionOrArray(MappingMongoConverter.java:1123)
        at org.springframework.data.mongodb.core.convert.MappingMongoConverter.readValue(MappingMongoConverter.java:1582)
        at org.springframework.data.mongodb.core.convert.MappingMongoConverter$MongoDbPropertyValueProvider.getPropertyValue(MappingMongoConverter.java:1482)
        at org.springframework.data.mongodb.core.convert.MappingMongoConverter$AssociationAwareMongoDbPropertyValueProvider.getPropertyValue(MappingMongoConverter.java:1531)
        at org.springframework.data.mongodb.core.convert.MappingMongoConverter$AssociationAwareMongoDbPropertyValueProvider.getPropertyValue(MappingMongoConverter.java:1494)
        at org.springframework.data.mapping.model.PersistentEntityParameterValueProvider.getParameterValue(PersistentEntityParameterValueProvider.java:74)
```

Do you need any minimal example? This was "censored" and taken from huge project.

Thanks

**Comment by mp911de** [comment] 2021-05-23 18:37
Please annotate your domain types with `@Document`. The type alias annotation isn't sufficient to associate entity classes with the `MongoMappingContext`. The entity scan at application startup discovers and registers type aliases for proper instantiation.

**Comment by joaoluis89** [comment] 2021-05-31 19:29
Hi, is anyone looking for this? I have just steped on those problems while deserializing concrete classes that implements a interface. `@TypeAlias` didn`t worked for me either

**Comment by legas1** [comment] 2021-06-01 06:09
@joaoluis89 @Document annotation helped me, did you tried it too?

**Comment by DevAtHeart** [comment] 2021-06-03 15:31
@legas1 what about types that are not top-level documents but sub-objects but still need type alias because of polymorphism?

for instance:

```kotlin
@Document
data class Zoo {
  var animals: List<Animal> = listOf()
}

abstract class Animal

@TypeAlias("zebra")
data class Zebra extends Animal

@TypeAlias("lion")
data class Lion extends Animal
```

Should Zebra and Lion be annotated with @Document as well?

**Comment by mp911de** [comment] 2021-06-07 06:47
Closing as entity scan of classes annotated with `@Document` works as designed.

**Closed by mp911de** 2021-06-07 06:47 UTC
Labels: status: invalid
