### ISSUE TITLE
Upgrade to Java 17

### ISSUE THREAD

**Issue by mp911de** [spring-projects/spring-data-mongodb#3756] opened 2021-07-29 13:02 UTC
```
[ERROR] Tests run: 2, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.006 s <<< FAILURE! - in org.springframework.data.mongodb.core.EntityOperationsUnitTests
[ERROR] org.springframework.data.mongodb.core.EntityOperationsUnitTests.shouldReportInvalidMetaField  Time elapsed: 0.005 s  <<< FAILURE!
java.lang.AssertionError: 

Expecting actual throwable to be an instance of:
  org.springframework.data.mapping.MappingException
but was:
  java.lang.reflect.InaccessibleObjectException: Unable to make private java.time.Instant(long,int) accessible: module java.base does not "opens java.time" to unnamed module @4bc42a8c
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:354)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
	at java.base/java.lang.reflect.Constructor.checkCanSetAccessible(Constructor.java:188)
	...(96 remaining lines not displayed - this can be changed with Assertions.setMaxStackTraceElementsDisplayed)
	at org.springframework.data.mongodb.core.EntityOperationsUnitTests.shouldReportInvalidMetaField(EntityOperationsUnitTests.java:47)
```

See also spring-projects/spring-data-commons#2423

**Comment by christophstrobl** [comment] 2021-07-29 14:38
duplicate of #3749. should be fixed by #3752

**Closed by christophstrobl** 2021-07-29 14:38 UTC
Labels: status: waiting-for-triage
