### ISSUE TITLE
Is it possible to use aggregation update in BulkOperations?

### ISSUE THREAD

**Issue by LeonLiu-Hiretual** [spring-projects/spring-data-mongodb#4340] opened 2023-03-22 03:38 UTC
Hi, I would like to use aggregation update in spring data mongo BulkOperations

MongoTemplate's update function support AggregationUpdate, e.g
`UpdateResult updateMulti(Query query, UpdateDefinition update, String collectionName);`
this would accept AggregationUpdate.

but currently in BulkOperations it only supports
`BulkOperations upsert(List<Pair<Query, Update>> updates);`

I am wondering if it could support aggregation update in bulk upsert like
`BulkOperations upsert(List<Pair<Query, UpdateDefinition>> updates);`

Thanks!

**Comment by christophstrobl** [comment] 2023-03-22 06:07
This is not yet supported. Closing as duplicate of: #3872

**Closed by christophstrobl** 2023-03-22 06:07 UTC
Labels: status: duplicate
