### ISSUE TITLE
Different result using Criteria and NearQuery using the same point and distance

### ISSUE THREAD

**Issue by chris-no1** [spring-projects/spring-data-mongodb#3614] opened 2021-03-29 09:59 UTC
I get different result when using the _Criteria_ opposed to _NearQuery_ with the same distance in kilometres. The Criteria can be used with the legacy and current version if I understand correctly. The _nearSphere_  defaults to meters instead of radians which alignes with [MongoDB manual documentation](https://docs.mongodb.com/manual/reference/operator/query/nearSphere/#op._S_nearSphere) for version 4.4. 

The test-case;
The distance between the two points in a straight line is 6.41375 km. 

Using the _Criteria_ with the _nearSphere_ for query will be successfully even when distance set to 10 meters.

```
@Override
    public List<GeometryObject> nearPointMaxDistance(GeoJsonPoint geojsonPoint, Distance maxDistance) {
        log.debug("Max distance {} - from point: {}", maxDistance.toString(), geojsonPoint.toString());
        Point point = new Point(geojsonPoint.getX(), geojsonPoint.getY());
        Criteria criteria = Criteria.where(COORDINATE_FIELD_NAME).nearSphere(point).maxDistance(maxDistance.getValue());
        final Query query = new Query();                
        query.addCriteria(criteria);
        log.debug("MongoDB JSON Query: {}", query.toString());
        return template.find(query, GeometryObject.class);        
    }
```
The other implementation using the _NearQuery_ work as expected.
```
@Override
    public GeoResults<GeometryObject> geoNearPointMaxDistance(GeoJsonPoint geojsonPoint, Distance maxDistance) {
        final NearQuery nearQuery = NearQuery.near(geojsonPoint).maxDistance(maxDistance).spherical(true);
        //log.debug("MongoDB JSON Query: {}", nearQuery.);
        return template.geoNear(nearQuery, GeometryObject.class);                
    }
```
The Spring documentation for  [GeoSpatial Queries](https://docs.spring.io/spring-data/mongodb/docs/current/reference/html/#core.web.basic.jackson-mappers) doest not specify or mention that  _nearSphere_ on the _Criteria_ reverts to radians. Shouldn't the two implementation yield the same result when kilometers is specified or am I missing something?

Please see the [Stackoverflow post](https://stackoverflow.com/questions/66334745/different-result-using-criteria-and-nearquery-using-the-same-point-and-distance) for the compete test code and implementation.

I am using Spring Boot / spring-boot-starter-parent = 2.4.3

Greetings Chris.

**Comment by christophstrobl** [comment] 2021-04-06 07:59
The issue originates in `Criteria.maxDistance` not being aware of the `Metric` to be used since it is a plain `long` value.
Converting the given value into the target format (defined by the geo representation used when constructing the query) is required in this case. 

`Criteria.nearSphere` with `Point` issues a query in legacy format (using radians)

```json
{ "coordinates" : 
	{ "$nearSphere" : 
		{ 
			"x" : 12.016907930374146, 
			"y" : 57.65644872952383
		}, 
		"$maxDistance" : 0.01 
	}
}
``` 

Passing in a `GeoJsonPoint` will use `$geometry` along with meters.

```json
{ "coordinates" : 
	{ "$nearSphere" :  
		{ "$geometry"  : 
			{ 
				"type" : "Point",
        			"coordinates" : [ 12.016907930374146, 57.65644872952383 ]
        	}
    	},
    	"$maxDistance" : 0.01 
    }
}
```

`NearQuery.maxDistance` on the other hand can work with `Distance` directly and is therefore capable of doing the conversion.

**Comment by chris-no1** [comment] 2021-04-09 08:10
Passing the _GeoJsonPoint_ instead of the _Point_ will always return false what ever distance I use. I've tried passing 70 km which should return the point that is 6.42 km away.

The query from the Criteria with the GeoJsonPoint look like this;

`nearPointMaxDistance: Query: { "coordinates" : { "$nearSphere" : { "$geometry" : { "$java" : Point [x=12.016908, y=57.656449] }, "$maxDistance" : 70.0 } } }`

According to the [Criteria javadoc](https://docs.spring.io/spring-data/mongodb/docs/current/api/) there is not version of _nearSphere_ that excepts _GeoJsonPoint_, only _Point_ according to the version of Spring v5.3.4 I'm running. But it seam to accept _GeoJsonPoint_ anyway an add  the _$geometry_  parameter. How does your version of the _Criteria_ function looks like? 

By the way, how do you log a clean MongoDB query that I can test in _mongo_ CLI directly. Only the _nearSphere_ toString() log the above query, but not the _NearQuery_?

**Comment by christophstrobl** [comment] 2021-04-09 09:18
`$nearSphere` `$maxDistance` is in `meters`. So it should be `7000` not `70`.

**Comment by chris-no1** [comment] 2021-04-09 09:37
I see, the _maxDistance_ input is double. Shouldn't the _Criteria_ also have _maxDistance_ Distance input variation like the _NearQuery_ since it support GeoJsonPoint?

**Comment by christophstrobl** [comment] 2022-01-19 12:43
Closing this one as it seems to work as designed - For changes to `Criteria` please file a new issue to discuss a potential enhancement there. Thank you!

**Closed by christophstrobl** 2022-01-19 12:43 UTC
Labels: status: waiting-for-triage
