### ISSUE TITLE
DocumentReference Proxy object(lazy) is not running properly

### ISSUE THREAD

**Issue by blueiceprj** [spring-projects/spring-data-mongodb#3854] opened 2021-10-05 15:30 UTC
In my case I have a nested referenced object like this.

```
public class GradeLevel 
{
	@MongoId(targetType = FieldType.OBJECT_ID)
	private String id;

	@DocumentReference(lazy = true)
	private GradeLevel nextGradeLevel;
```
I get a document using repository with findOne. I just want to check circular references. If the database reference value of nextGradeLevel is getting null pointer error. 

```
	public void hasCircularReference(GradeLevel level)
	{
		GradeLevel parent = level;
		while (parent.getNextGradeLevel() != null)
		{
                        // Only to check If Id value is null
			if (parent.getNextGradeLevel().getId() == null) {
				System.out.println("EMPTY");
			}
			final GradeLevel child = repository.findById(parent.getNextGradeLevel().getId())
					.orElseThrow(() -> ApiException.builder().message("Next Grade Level not found").status(Status.NOT_FOUND).build());
                         ................................
			hasCircularReference(child);
		}
	}

```

```
        @Override
	public Optional<T> findById(String id)
	{
		objectIdCheck(id, "id");
		final Query query = new Query();
		query.addCriteria(Criteria.where("_id").is(new ObjectId(id)));
		return Optional.ofNullable(template.findOne(query, collectionType));
	}

```
<img width="993" alt="Ekran Resmi 2021-10-05 17 01 34" src="https://user-images.githubusercontent.com/1829975/136052788-f6fc74e2-abd6-4719-8c4b-7903db39b4a1.png">

**Comment by christophstrobl** [comment] 2021-11-11 14:52
If you would like us to spend some time helping you to diagnose the problem, please spend some time describing it. Right now, we struggle to understand what you want to achieve.

**Comment by blueiceprj** [comment] 2021-11-12 07:47
Actually the problem is simple. When the document reference is lazy loaded  it return as null. But the document and its reference are exist on db.

**Comment by blueiceprj** [comment] 2021-11-16 10:55
And while reference data is not exist in database then the documentreference object must be return null. In my case documentreference object is not null but reference value is null. For example.

`doc.getReferenceObject() != null `

but

`doc.getReferenceObject().getId()  == null`


if the "Id" is null .....getReferenceObject() must return null value. Because of that we have to double check on our code.

When I check the referencedocument is null or other value it return value from proxy object. And I think spring assign a proxy object for each documentreference annotation and it gets return not null. But actually the value is null.

**Comment by christophstrobl** [comment] 2022-01-19 12:39
We've not been able to reproduce the problem given the description above. Please take the time to provide a complete [minimal sample](https://stackoverflow.com/help/minimal-reproducible-example) (something that we can unzip or git clone, build, and deploy) that reproduces the problem to help us diagnose the issue.

**Comment by spring-projects-issues** [comment] 2022-01-26 12:42
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-projects-issues** [comment] 2022-02-02 12:42
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-projects-issues** 2022-02-02 12:42 UTC
Labels: status: waiting-for-feedback, status: feedback-reminder
