### ISSUE TITLE
Connection to MongoDB Atlas lost, error "cannot find user account after reload"

### ISSUE THREAD

**Issue by tomas-laubr-smart-software** [spring-projects/spring-data-mongodb#3584] opened 2021-03-09 18:12 UTC
We have a Spring Boot app. Spring Boot version 2.4.2. We have encounter this error, when checking health status on /actuator/health

```
2021-03-09 10:21:48.858  WARN --- [nio-8080-exec-7] o.s.b.a.mongo.MongoHealthIndicator       : MongoDB health check failed
org.springframework.data.mongodb.UncategorizedMongoDbException: Command failed with error 8000 (AtlasError): 'cannot find user account after reload' on server portalcluster-shard-00-01.jhsdc.mongodb.net:27017. The full response is 
{
    "ok": 0,
    "errmsg": "cannot find user account after reload",
    "code": 8000,
    "codeName": "AtlasError"
}
; nested exception is com.mongodb.MongoCommandException: Command failed with error 8000 (AtlasError): 'cannot find user account after reload' on server portalcluster-shard-00-01.jhsdc.mongodb.net:27017. The full response is 
{
    "ok": 0,
    "errmsg": "cannot find user account after reload",
    "code": 8000,
    "codeName": "AtlasError"
}

	at org.springframework.data.mongodb.core.MongoExceptionTranslator.translateExceptionIfPossible(MongoExceptionTranslator.java:133)
	at org.springframework.data.mongodb.core.MongoTemplate.potentiallyConvertRuntimeException(MongoTemplate.java:2882)
	at org.springframework.data.mongodb.core.MongoTemplate.execute(MongoTemplate.java:537)
	at org.springframework.data.mongodb.core.MongoTemplate.executeCommand(MongoTemplate.java:453)
	at org.springframework.boot.actuate.mongo.MongoHealthIndicator.doHealthCheck(MongoHealthIndicator.java:46)
	at org.springframework.boot.actuate.health.AbstractHealthIndicator.health(AbstractHealthIndicator.java:82)
	at org.springframework.boot.actuate.health.HealthIndicator.getHealth(HealthIndicator.java:37)
	at org.springframework.boot.actuate.health.HealthEndpointWebExtension.getHealth(HealthEndpointWebExtension.java:85)
	at org.springframework.boot.actuate.health.HealthEndpointWebExtension.getHealth(HealthEndpointWebExtension.java:44)
	at org.springframework.boot.actuate.health.HealthEndpointSupport.getContribution(HealthEndpointSupport.java:99)
	at org.springframework.boot.actuate.health.HealthEndpointSupport.getAggregateHealth(HealthEndpointSupport.java:110)
	at org.springframework.boot.actuate.health.HealthEndpointSupport.getContribution(HealthEndpointSupport.java:96)
	at org.springframework.boot.actuate.health.HealthEndpointSupport.getHealth(HealthEndpointSupport.java:74)
	at org.springframework.boot.actuate.health.HealthEndpointSupport.getHealth(HealthEndpointSupport.java:61)
	at org.springframework.boot.actuate.health.HealthEndpointWebExtension.health(HealthEndpointWebExtension.java:71)
	at org.springframework.boot.actuate.health.HealthEndpointWebExtension.health(HealthEndpointWebExtension.java:60)
	at jdk.internal.reflect.GeneratedMethodAccessor248.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.springframework.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:282)
	at org.springframework.boot.actuate.endpoint.invoke.reflect.ReflectiveOperationInvoker.invoke(ReflectiveOperationInvoker.java:77)
	at org.springframework.boot.actuate.endpoint.annotation.AbstractDiscoveredOperation.invoke(AbstractDiscoveredOperation.java:60)
	at org.springframework.boot.actuate.endpoint.web.servlet.AbstractWebMvcEndpointHandlerMapping$ServletWebOperationAdapter.handle(AbstractWebMvcEndpointHandlerMapping.java:290)
	at org.springframework.boot.actuate.endpoint.web.servlet.AbstractWebMvcEndpointHandlerMapping$OperationHandler.handle(AbstractWebMvcEndpointHandlerMapping.java:373)
	at jdk.internal.reflect.GeneratedMethodAccessor247.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:197)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:141)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:106)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:894)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:808)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1060)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:962)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:898)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:626)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:733)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)

```

From that moment all connections ended by the error. However after restarting the app it started working again.

So the problem is, that whatever caused the error for the first time was ok again, but the Spring app wasn't.
I believe this is a bug. That the connection is not established again without application restart.

We had two same servers (two same Spring boot apps), different environments (different connection strings to different clusters in Atlas) which behaved same - they encountered the same error today morning for the first time and refused to work with Mongo until they have been restarted. 

I got no resolution from MongoDB Atlas support. They told me "I can confirm there are no outages, and your cluster is reporting as healthy"

**Comment by christophstrobl** [comment] 2021-03-10 06:30
@jyemin your input would be welcome!

**Comment by spring-projects-issues** [comment] 2021-03-17 06:33
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by jyemin** [comment] 2021-03-19 12:25
FYI, the conversation about this error has moved to https://developer.mongodb.com/community/forums/t/mongodb-atlas-returns-error-cannot-find-user-account-after-reload/98422

**Comment by christophstrobl** [comment] 2021-03-19 12:30
Thank you @jyemin - I'll close this one then.

**Closed by christophstrobl** 2021-03-19 12:30 UTC
Labels: status: feedback-provided

**Comment by tomas-laubr-smart-software** [comment] 2021-03-22 11:12
Hello. What do you by "the conversation about this error has moved"? It's rather exact opposite. I started the conversation in the forum. But then I have decided to fill a bug report here.
There is no ongoing conversation in the forum.  I'm rather waiting for confirmation from you, that the problem I have encountered is a bug in Spring or not.

**Comment by jyemin** [comment] 2021-03-22 12:58
The underlying error is coming from a MongoDB server running in Atlas, and does not look like one that could be caused by a bug in the MongoDB driver, Spring, or your application.  So I think it's more appropriate to follow up on a MongoDB forum.  We are working on a root-cause analysis and will update the linked forum post soon.

**Comment by tomas-laubr-smart-software** [comment] 2021-03-22 13:03
I see. You have moved the conversation to the forum.

However please note this issue is not about the error itself. It's more about the fact Spring was not able to recover from the error.

**Comment by jyemin** [comment] 2021-03-23 14:12
@tomas-laubr-smart-software I see what you're saying now.  I was focused on understanding the root cause of the error being reported by Atlas. We can proceed with that investigation on the forum post that you started.

As for error recovery: generally the MongoDB Java driver (and Spring as well, as it's built on top of the driver) should recover from any transient issue with the server, without requiring a restart of the application.  Any chance that you still have the application logs for the period from first failure up until the restart?  Usually logs are required to proceed with an investigation for an issue such as this.  If so, can you post them somewhere so we can take a look?

**Comment by tomas-laubr-smart-software** [comment] 2021-03-23 16:11
Sory, no, unfortunately I don't have the logs anymore...
