### ISSUE TITLE
Reactive MongoDb Transactions not working for saveAll()

### ISSUE THREAD

**Issue by aby-kuruvilla-clear** [spring-projects/spring-data-mongodb#4067] opened 2022-05-27 15:16 UTC
When I use saveAll() method, The transaction is not getting rolled back but works for save()
Following is my MongoConfig

 ```
@Bean("reactiveMongoClientGST")
    public MongoClient reactiveMongoClientGST() {
        return MongoClients.create(createMongoClientSettings(customMongoProperties.getGst()));
    }

    @Bean("tenantMongoDatabase")
    public MongoDatabase getTenantMongoDatabase(@Qualifier("reactiveMongoClientGST") MongoClient mongoClient) {
        return mongoClient.getDatabase(customMongoProperties.getGst().getDatabase());
    }

    @Bean("mongoTemplateTenant")
    public ReactiveMongoTemplate reactiveMongoTemplateGST(
            @Qualifier("reactiveMongoClientGST") MongoClient mongoClient) {
        ReactiveMongoTemplate reactiveMongoTemplate = new ReactiveMongoTemplate(mongoClient,
                customMongoProperties.getGst().getDatabase());
        return reactiveMongoTemplate;
    }

    @Bean("tenantTransactionOperator")
    public TransactionalOperator tenantTransactionOperator(
            @Qualifier("tenantTransactionManager") ReactiveTransactionManager reactiveTransactionManager) {
        return TransactionalOperator.create(reactiveTransactionManager);
    }

    @Bean("tenantTransactionManager")
    public ReactiveMongoTransactionManager tenantTransactionManager(
            @Qualifier("tenantMongoDbFactory") ReactiveMongoDatabaseFactory rdbf) {
        return new ReactiveMongoTransactionManager(rdbf);
    }

    @Bean("tenantMongoDbFactory")
    public SimpleReactiveMongoDatabaseFactory tenantReactiveMongoDatabaseFactory(
            @Qualifier("reactiveMongoClientGST") MongoClient mongo) {
        String database = customMongoProperties.getGst().getDatabase();
        return new SimpleReactiveMongoDatabaseFactory(mongo, database);
    }
```
Installed enterprise MongoDB with replicaset configuration.
Enabled the transactions like this
`@EnableTransactionManagement(mode = AdviceMode.PROXY)
`
Then finally wrote a service method like this which called from another class.
`@Transactional(transactionManager = "tenantTransactionManager")
    public Mono<Void> saveInvoice(Flux<Invoice> invoice) {
        return salesInvoiceRepo.saveAll(invoice)
                .thenMany(salesLineItemRepository.insert(toSalesLineItems(invoice))).then();
    }`

When there is an error in the thenMany() , the previous save is not getting reverted. However when I use one by one save like this the transaction is working.
`@Transactional(transactionManager = "tenantTransactionManager")
    public Mono<Void> saveInvoice(Invoice invoice) {
        return salesInvoiceRepo.save(invoice)
                .thenMany(salesLineItemRepository.insert(toSalesLineItems(invoice))).then();
    }`
    
PS: We have two MongoDB configs in the same project and but we are not saving to both DB servers at the same time. Both salesLineItemRepository and salesInvoiceRepo are in the same server and db.

**Comment by christophstrobl** [comment] 2022-08-01 14:21
If you'd like us to spend some time investigating, please take the time to provide a complete [minimal sample](https://stackoverflow.com/help/minimal-reproducible-example) (something that we can unzip or git clone, build, and deploy) that reproduces the problem.

**Comment by spring-projects-issues** [comment] 2022-08-08 14:25
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-projects-issues** [comment] 2022-08-15 14:25
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-projects-issues** 2022-08-15 14:25 UTC
Labels: status: waiting-for-feedback, status: feedback-reminder
