### ISSUE TITLE
Spring Data Mongo fails while converting the Document to Object type

### ISSUE THREAD

**Issue by logztechstuff** [spring-projects/spring-data-mongodb#4162] opened 2022-09-12 18:10 UTC
We have a POJO class that contains the Map with key type as String and value type as Object (Map<String, Object>). Until version 3.1, the Document from DB is converted properly to Map<String, Object>. Once we upgraded to 3.2, the conversion is failing with an error,

org.springframework.data.mapping.MappingException: Expected to read Document Document{<hidden>} into type class java.lang.Object but didn't find a PersistentEntity for the latter!

The read method of MappingMongoConvertor had a statement,
`if (typeToUse.equals(ClassTypeInformation.OBJECT)) {
	return (S) bson;
  }`

But the above code is not available in the latest versions of the MappingMongoConvertor.

Please help us with how to solve this problem.

Thanks in advance.

**Comment by christophstrobl** [comment] 2022-09-13 05:27
If you'd like us to spend some time investigating, please take the time to provide a complete [minimal sample](https://stackoverflow.com/help/minimal-reproducible-example) (something that we can unzip or git clone, build, and deploy) that reproduces the problem.

**Comment by logztechstuff** [comment] 2022-09-13 06:10
Hi @christophstrobl 
Thanks for the response. Ours is a very large project, so didn't share the sample. I will work on a small project with a similar use case and share it. Thanks again.

**Comment by mp911de** [comment] 2022-09-13 12:14
See also https://stackoverflow.com/questions/73689924/spring-data-mongo-conversion-is-not-working-for-object-type-since-version-3-2

**Comment by christophstrobl** [comment] 2023-03-09 10:42
Closing this one because we cannot reproduce the issue.

**Closed by christophstrobl** 2023-03-09 10:42 UTC
Labels: status: feedback-provided
