### ISSUE TITLE
Pagination performance issue.

### ISSUE THREAD

**Issue by Jyoti-Ranjan-8** [spring-projects/spring-data-mongodb#4150] opened 2022-08-30 13:00 UTC
I am passing pageable object in repository method to achieve  pagination. It giving correct data, but the aggregate query executed by frame work is taking time.
is there is a way to avoid this scenario.

Here is the code I am using for pagination:
`Page<ProductReview> findByProductIdAndDomainId(String productId, String domainId, Pageable page);`

Note : The product_review collection contains 10 millions data, inside this some product having more that 50k records

**Comment by mp911de** [comment] 2022-08-30 13:35
If you would like us to spend some time helping you to diagnose the problem, please spend some time describing it and, ideally, providing a [minimal sample](https://stackoverflow.com/help/mcve) that reproduces the problem. As we're discussing performance issues, it would be good to have JMH-based benchmarks to capture the current performance behavior and to get an idea what you expect.

**Comment by spring-projects-issues** [comment] 2022-09-06 13:36
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-projects-issues** [comment] 2022-09-13 13:36
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-projects-issues** 2022-09-13 13:36 UTC
Labels: status: waiting-for-feedback, status: waiting-for-triage, status: feedback-reminder
