### ISSUE TITLE
ClassCastException in MappingMongoConverter when having Map<String, Object> as a field type.

### ISSUE THREAD

**Issue by Taha-Di-Nero** [spring-projects/spring-data-mongodb#3692] opened 2021-07-01 13:05 UTC
After upgrading to Spring Boot from 2.4.4 to 2.5.2(spring-data-mongodb 3.1.6 --> 3.2.2) I am having the following exception:
```bash
Caused by: java.lang.ClassCastException: java.util.LinkedHashMap incompatible with org.bson.conversions.Bson
	at org.springframework.data.mongodb.core.convert.MappingMongoConverter$ConversionContext.convert(MappingMongoConverter.java:1905)
	at org.springframework.data.mongodb.core.convert.MappingMongoConverter$MongoDbPropertyValueProvider.getPropertyValue(MappingMongoConverter.java:1636)
	at org.springframework.data.mongodb.core.convert.MappingMongoConverter.readProperties(MappingMongoConverter.java:477)
	at org.springframework.data.mongodb.core.convert.MappingMongoConverter.populateProperties(MappingMongoConverter.java:392)
	at org.springframework.data.mongodb.core.convert.MappingMongoConverter.read(MappingMongoConverter.java:371)
	at org.springframework.data.mongodb.core.convert.MappingMongoConverter.readDocument(MappingMongoConverter.java:341)
	at org.springframework.data.mongodb.core.convert.MappingMongoConverter.read(MappingMongoConverter.java:277)
	at org.springframework.data.mongodb.core.convert.MappingMongoConverter.read(MappingMongoConverter.java:273)
	at org.springframework.data.mongodb.core.convert.MappingMongoConverter.read(MappingMongoConverter.java:102)
	at org.springframework.data.mongodb.core.MongoTemplate$ReadDocumentCallback.doWith(MongoTemplate.java:3178)
	at org.springframework.data.mongodb.core.MongoTemplate.executeFindMultiInternal(MongoTemplate.java:2813)
	at org.springframework.data.mongodb.core.MongoTemplate.doFind(MongoTemplate.java:2543)
	at org.springframework.data.mongodb.core.MongoTemplate.doFind(MongoTemplate.java:2525)
	at org.springframework.data.mongodb.core.MongoTemplate.find(MongoTemplate.java:847)
	at org.springframework.data.mongodb.repository.support.SimpleMongoRepository.findAll(SimpleMongoRepository.java:428)
	at org.springframework.data.mongodb.repository.support.SimpleMongoRepository.findAllById(SimpleMongoRepository.java:162)
```

In the domain object there is a the following property:
`protected Map<String, Object> _flexFields = new HashMap<>()`

When `MappingMongoConverter` try to convert it in line `1905`, the exception is thrown even the map is empty.
The 3.1.x `MappingMongoConverter` implementation works fine.
Please some fix.

**Comment by christophstrobl** [comment] 2021-07-01 15:55
Thanks for reporting can you please add the domain types involved as well as the raw document representation. Ideally you have a complete [minimal sample](https://stackoverflow.com/help/minimal-reproducible-example) (something that we can unzip or git clone, build, and deploy) that reproduces the problem.
This would help us to better understand the issue.

**Comment by Taha-Di-Nero** [comment] 2021-07-01 16:17
I will try but in 3.1.x there was no cast to Bson

`if (typeHint.isMap()) {
				return (S) mapConverter.convert(this, (Bson) source, typeHint);
			}`

**Comment by Taha-Di-Nero** [comment] 2021-07-05 14:02
[minimal_sample.zip](https://github.com/spring-projects/spring-data-mongodb/files/6764734/minimal_sample.zip)
Here is a minimal sample to reproduce the error. It works with **3.1.x** but not with **3.2.2**

**Comment by christophstrobl** [comment] 2021-07-06 12:10
The java driver uses `org.bson.Document` to represent `Map` structures. the `_flexFields` is actually not present in the source when reading from MongoDB. However the `FlexDocumentListener` puts in a `LinkedHashMap` via the `afterLoad` event which then in turn leads to the error you see.

I admit the restriction in place is a kinda hard one and I'll take this to the team to see if we want it to be softened to something like:
```java
if (typeHint.isMap()) {
	if(source instanceof Bson) {
		return (S) mapConverter.convert(this, (Bson) source, typeHint);
	}
	if(source instanceof Map) {
		return (S) mapConverter.convert(this, new Document((Map<String,Object>)source), typeHint);
	}
	throw new IllegalArgumentException(String.format("Expected map like structure but found %s", source.getClass()));
}
``` 

For the time being please `org.bson.Document` when adding map like structures to an existing document.

**Comment by mp911de** [comment] 2021-07-15 07:59
Closing as duplicate of #3702

**Closed by mp911de** 2021-07-15 07:59 UTC
Labels: status: waiting-for-triage
