### ISSUE TITLE
ConverterNotFoundException: No converter found capable of converting from type [org.bson.types.Binary] to type [java.util.UUID]

### ISSUE THREAD

**Issue by Logicko** [spring-projects/spring-data-mongodb#4076] opened 2022-06-03 11:45 UTC
**Given :**
-OpenJDK 11
-Intellij IDEA
-Spring boot version : 2.5.12
-Spring data mongodb version : 3.2.10 (Mongo driver 4.2.3)

**When:**
`
@Bean
public MongoTemplate mongoTemplate() throws Exception {
     return new MongoTemplate(mongoClient(), database);
}
`

**Then get error:**
`
ConverterNotFoundException: No converter found capable of converting from type [org.bson.types.Binary] to type  [java.util.UUID]
`

**Cause:**
`private MongoTemplate(MongoDatabaseFactory dbFactory, MongoTemplate that)`

IS CALLED FROM
`public MongoTemplate(MongoClient mongoClient, String databaseName)`

EVEN THOUGH the cast to `(MongoConverter)((MongoConverter)null`

The constructor `public MongoTemplate(MongoDatabaseFactory mongoDbFactory, @Nullable MongoConverter mongoConverter)` should be called ?

Thanks,

**Comment by Logicko** [comment] 2022-06-09 12:18
Resolved By adding converters to `MongoTemplate` like this :

```
@Bean
public MongoTemplate mongoTemplate() throws Exception {
    MongoTemplate template = new MongoTemplate(mongoClient(), database);
    MappingMongoConverter mmc = (MappingMongoConverter)template.getConverter();
    mmc.setCustomConversions( new MongoCustomConversions(asList(
            new MongoConverters.BinaryToUuidConverter(),
            new MongoConverters.UuidToBinaryConverter()
    )));
    mmc.afterPropertiesSet();
    return template;
}
```

```
public static class BinaryToUuidConverter implements Converter<Binary, UUID> {
    @Override
    public UUID convert(@NonNull Binary binary) {
        ByteBuffer byteBuffer = ByteBuffer.wrap(binary.getData());
        long high = byteBuffer.getLong();
        long low = byteBuffer.getLong();
        return new UUID(high, low);
    }
}
```
```
public static class UuidToBinaryConverter implements Converter<UUID, Binary> {
    @Override
    public Binary convert(@NonNull UUID uuid) {
        ByteBuffer bb = ByteBuffer.wrap(new byte[16]);
        bb.putLong(uuid.getMostSignificantBits());
        bb.putLong(uuid.getLeastSignificantBits());
        return new Binary(bb.array());
    }
}
```

**Comment by christophstrobl** [comment] 2022-08-01 14:19
If you'd like us to spend some time investigating, please take the time to provide a complete [minimal sample](https://stackoverflow.com/help/minimal-reproducible-example) (something that we can unzip or git clone, build, and deploy) that reproduces the problem.

**Comment by spring-projects-issues** [comment] 2022-08-08 14:20
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-projects-issues** [comment] 2022-08-15 14:20
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-projects-issues** 2022-08-15 14:20 UTC
Labels: status: waiting-for-feedback, status: feedback-reminder
