### ISSUE TITLE
 mongoTemplate.updateMulti

### ISSUE THREAD

**Issue by a13237009879** [spring-projects/spring-data-mongodb#3578] opened 2021-03-02 09:25 UTC
Using spring boot data Mongo mongoTemplate.updateMulti Method, an unrecognized command $isolated appears occasionally, and the actual number of splicing query parameters is not spliced and set。

  // update mongo：将相应mongo消息数据标记为已删除
            mongoTemplate.updateMulti(
                    new Query().addCriteria(
                            Criteria.where(MsgConstant.FIELD_MSGID).lte(maxMsgId)
                                    .and(MsgConstant.FIELD_NODEID).is(getNodeId(userId, friendId))
                                    .and(MsgConstant.FIELD_MSGSTATE).ne(MsgStateEnum.CLEAR.getType())
                    ),
                    Update.update(MsgConstant.FIELD_MSGSTATE, MsgStateEnum.CLEAR.getType()),
                    "msg_c2c");

**Comment by christophstrobl** [comment] 2021-03-02 09:32
Could you please provide more information on what you're trying to do? 
Which version are you using, when does it happen, what does your setup (configuration, domain types, calling code) look like?
Ideally you can provide a [Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example) to help us understand/spot the issue.

**Comment by a13237009879** [comment] 2021-03-02 09:41
Client version:

<dependency>

<groupId> org.springframework.boot </groupId>

<artifactId>spring-boot-starter-data-mongodb</artifactId>

<version>2.2.0.RELEASE</version>

</dependency>

Mongodb server version: 4.2.8



Use example:

mongoTemplate.updateMulti (

new Query().addCriteria(

Criteria.where ( MsgConstant.FIELD_ MSGID).lte(maxMsgId)

.and( MsgConstant.FIELD_ USERID).is(userId)

.and( MsgConstant.FIELD_ NODEID).is(getNodeId(userId, friendId))

.and( MsgConstant.FIELD_ MSGSTATE).ne( MsgStateEnum.CLEAR.getType ())

),

Update.update ( MsgConstant.FIELD_ MSGSTATE, MsgStateEnum.CLEAR.getType ()),

"msg_ c2c");




In the formal run time, an illegal operator with error report is occasionally found: $isolated

**Comment by christophstrobl** [comment] 2021-03-02 09:51
Please check if there's an unintentional call to `Update.isolated()`. Per default `isolated` is set to `false` and not included in the update `Document`.

**Comment by a13237009879** [comment] 2021-03-02 09:56
The complete method is as follows, there is no call. Production is also occasionally wrong, after the emergence began to appear frequently.

 

private void deleteMsg(DeleteSingleChatDTO deleteSingleChatDTO) {
        boolean both = deleteSingleChatDTO.getBoth();
        Long maxMsgId = deleteSingleChatDTO.getMaxMsgId();
        Long friendId = deleteSingleChatDTO.getFriendId();
        Long userId = deleteSingleChatDTO.getUserId();
        if (both) {
            // update mongo：将相应mongo消息数据标记为已删除
            mongoTemplate.updateMulti(
                    new Query().addCriteria(
                            Criteria.where(MsgConstant.FIELD_MSGID).lte(maxMsgId)
                                    .and(MsgConstant.FIELD_NODEID).is(getNodeId(userId, friendId))
                                    .and(MsgConstant.FIELD_MSGSTATE).ne(MsgStateEnum.CLEAR.getType())
                    ),
                    Update.update(MsgConstant.FIELD_MSGSTATE, MsgStateEnum.CLEAR.getType()),
                    "msg_c2c");
        } else {
            //update mongo：将相应mongo消息数据标记为清空
            mongoTemplate.updateMulti(
                    new Query().addCriteria(
                            Criteria.where(MsgConstant.FIELD_MSGID).lte(maxMsgId)
                                    .and(MsgConstant.FIELD_USERID).is(userId)
                                    .and(MsgConstant.FIELD_NODEID).is(getNodeId(userId, friendId))
                                    .and(MsgConstant.FIELD_MSGSTATE).ne(MsgStateEnum.CLEAR.getType())
                    ),
                    Update.update(MsgConstant.FIELD_MSGSTATE, MsgStateEnum.CLEAR.getType()),
                    "msg_c2c");
        }
    }

**Comment by a13237009879** [comment] 2021-03-02 09:58
Is there any other mechanism to trigger automatic increase of isolation conditions?

**Comment by christophstrobl** [comment] 2021-03-02 10:14
The only other way would be to include `$isolated` in the `Query` directly, eg. by doing something like this:
```java
new BasicQuery("{'field':'value', '$isolated' : 1}")
```
Please provide a failing sample/test so we can see what's going on, as I don't think we can support you otherwise.

**Comment by spring-projects-issues** [comment] 2021-03-09 10:18
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-projects-issues** [comment] 2021-03-16 10:18
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-projects-issues** 2021-03-16 10:18 UTC
Labels: status: feedback-reminder, status: waiting-for-feedback
