### ISSUE TITLE
reactive TransactionalOperator fails for some test cases

### ISSUE THREAD

**Issue by byhu** [spring-projects/spring-data-mongodb#3679] opened 2021-06-21 13:39 UTC
I have create some test cases at https://github.com/byhu/springMongoTxTest.git. Transaction failed 3 out of 6 cases.

for the flux(txo) case, the log show, it always have txnNumber: 1.  I used mongo atlas for my test, and it is accessable from anywhere IP, so you should be able to run the project without any modification.

```java

        // session synchronization doesn't seem to make any difference
        mongo.setSessionSynchronization(SessionSynchronization.ALWAYS);

        var txo = TransactionalOperator.create(new ReactiveMongoTransactionManager(factory), new DefaultTransactionDefinition());

        // test cases
        flux(txo);      // failed
//        monoZip(txo); // failed
//        fluxO(txo);   // failed, if you run multiple times, you will see 1 or 2 records of A1 inserted.

//        recursive(txo, 0).block(); // success
//        mono(txo);        // success
//        monoConcat(txo);  // success
    }

    private Mono<A2> save(int i) {
        var d0 = new A1(i, "asdf " + i);
        var d1 = new A2(i, "asdfadf " + i);
        return mongo.save(d0)
                .flatMap(it -> {
                    if (i % 20 == 19)
                        return Mono.error(new Exception("ddd"));
                    return Mono.empty();
                })
                .then(mongo.save(d1));
    }

    private Mono<Void> recursive(TransactionalOperator txo, int i) {
        if (i > 1000)
            return Mono.empty();
        return txo.transactional(save(i))
                .onErrorResume(e -> Mono.empty())
                .then(recursive(txo, i + 1));
    }

    private void flux(TransactionalOperator txo) {
        Flux.range(0, 1000)
                .flatMap(i -> txo.transactional(save(i)))
                .onErrorResume(e -> Mono.empty())
                .blockLast();
    }

    private void fluxO(TransactionalOperator txo) {
        txo.transactional(Flux.range(0, 1000)
                .flatMap(this::save))
                .blockLast();
    }

    private void mono(TransactionalOperator txo) {
        var l = IntStream.range(1, 1000).mapToObj(i -> txo.transactional(save(i))).collect(Collectors.toList());
        l.stream().reduce((a, b) -> a.then(b))
                .get()
                .block();
    }

    private void monoConcat(TransactionalOperator txo) {
        var  m = txo.transactional(save(0)).concatWith(txo.transactional(save(1)));
        for (int i = 2; i < 100; i++)
            m = m.concatWith(txo.transactional(save(i)));
        m.onErrorContinue((e, a) -> {})
                .blockLast();
    }

    private void monoZip(TransactionalOperator txo) {
        var l = IntStream.range(1, 1000).mapToObj(i -> txo.transactional(save(i))).collect(Collectors.toList());
        Mono.zip(l, a -> a)
                .onErrorResume(e -> Mono.empty())
                .block();
        System.exit(0);
    }
```

**Comment by mp911de** [comment] 2021-06-22 09:41
If you would like us to spend some time helping you to diagnose the problem, please spend some time describing it. Right now, we struggle to understand what you want to achieve.

**Comment by byhu** [comment] 2021-06-22 15:15
I spend a lot of time to craft the test cases. The test is to insert 2 docs into 2 collections in one transaction. 3 of my test cases fail because the count in the 2 collections are not the same. I have made the mongodb that used in the test public. you can simple run the test as is to see the problems. Let me know if you need more specifics.

**Comment by mp911de** [comment] 2021-06-22 15:22
The code isn't following any known structure of a JUnit or TestNG test unfortunately which makes it impossible to know the assertions. Reactive pipelines throw random errors without a description of whether this is expected or what the code is actually trying to simulate. Method names aren't expressing what they try to do. 

Since this ticket isn't actionable for us, I'm inclined to close it unless we can understand what you're trying to achieve and what exactly fails with a reproducible test case.

**Comment by byhu** [comment] 2021-06-23 17:13
I have updated the test cases to JUnit. There 2 test cases that will run successfully, But if you the flow terminate, you  will see there are discrepancies in db.
@Test flux(), if you uncomment line 64.  // System.exist(1);
@Test monoZip, if you uncomment line 79  // throw e;

**Comment by mp911de** [comment] 2021-07-20 08:27
I'm still not able to comprehend what the tests are trying to achieve. Given that this ticket isn't actionable, I'm closing it for now.

If you want us to understand the test setup, please provide a simple setup without recursions, reduce operators or intermediate errors that are thrown upon catching a magic integer value.

**Closed by mp911de** 2021-07-20 08:27 UTC
Labels: status: feedback-provided, status: waiting-for-triage
