### ISSUE TITLE
MatchOperation criteria type mismatch

### ISSUE THREAD

**Issue by blueiceprj** [spring-projects/spring-data-mongodb#3793] opened 2021-08-31 03:30 UTC
Spring data Mongodb 3.3.0.M2

When I use Criteria with MatchOperation "_id" field type mismatch error like this. Id is string not objectId. There is no problem with other fields.

```
String id = .....
final MatchOperation m = Aggregation.match(Criteria.where("_id").is(id));

Executing aggregation: [{ "$match" : { "_id" : { "$oid" : "5c5aa8551ad17423a4f6ef1d"}}}...
```

It must be output like this

`Executing aggregation: [{ "$match" : { "_id" : "5c5aa8551ad17423a4f6ef1d"}}...`

**Comment by blueiceprj** [comment] 2021-08-31 23:15
If I set the id as different format of ObjectId like this "1111111" it is working properly. 

`[{ "$match" : { "_id" : "111111", "deleted" : false, "gradeSettings.enableGrading" : true}}, ...]`

**Comment by blueiceprj** [comment] 2021-08-31 23:35
I think problem is here

<img width="797" alt="Ekran Resmi 2021-09-01 01 24 42" src="https://user-images.githubusercontent.com/1829975/131589037-01f421b0-be24-4d0f-960f-2a444064f664.png">

**Comment by christophstrobl** [comment] 2021-09-01 06:58
This sounds like the behaviour described in the [reference documentation](https://docs.spring.io/spring-data/mongodb/docs/current/reference/html/#mongo-template.id-handling) for mapping values to the _id_ field.
Did it behave differently on a previous version?

**Comment by blueiceprj** [comment] 2021-09-01 07:05
On previous version I used type as objectId. But now I converted to string type.

**Comment by christophstrobl** [comment] 2022-01-19 12:40
This still sounds like it behaves as documented. Please take the time to provide a complete [minimal sample](https://stackoverflow.com/help/minimal-reproducible-example) (something that we can unzip or git clone, build, and deploy) that reproduces the problem to help us diagnose the issue.

**Comment by spring-projects-issues** [comment] 2022-01-26 12:42
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-projects-issues** [comment] 2022-02-02 12:42
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-projects-issues** 2022-02-02 12:42 UTC
Labels: status: waiting-for-feedback, status: feedback-reminder
