### ISSUE TITLE
Binary Not Deserialized to byte[]

### ISSUE THREAD

**Issue by gtomassi** [spring-projects/spring-data-mongodb#3670] opened 2021-06-15 13:56 UTC
When upgrading to the latest driver release (3.1.7 -> 3.2.1), our unit tests break due to improper deserialization of type org.bson.types.Binary. For some reason it is no longer being deserialized to a byte[] and left as the Binary class.

**Comment by christophstrobl** [comment] 2021-06-15 14:15
Do you have the test handy? A complete [minimal sample](https://stackoverflow.com/help/minimal-reproducible-example) (something that we can unzip or git clone, build, and deploy) that reproduces the problem helps us a lot identify the issue.

**Comment by gtomassi** [comment] 2021-06-15 18:46
@christophstrobl Here you go..

- Output w/ 3.2.1 -> _OUT: TestDomainObject{foo='bar', value=org.bson.types.Binary@403}  -> SAME: false_
- Output w/ 3.1.7 -> _OUT: TestDomainObject{foo='bar', value=[B@14f6b800}  -> SAME: true_

```java
    public static class TestDomainObject<V> {

        protected String foo;
        protected V value;

        @Override
        public String toString() {
            return "TestDomainObject{" +
                    "foo='" + foo + '\'' +
                    ", value=" + value +
                    '}';
        }
    }

    @Test
    public void testBrokenExample() {

        ReactiveMongoOperations mongo = injector.getInstance(ReactiveMongoOperations.class);

        Query query = new Query(where("foo").is("bar"));
        mongo.upsert(query, new Update().set("value", new byte[] {0x00, 0x42}), "exampleCollection").block();
        TestDomainObject<?> out = mongo.findOne(query, TestDomainObject.class, "exampleCollection").block();

        System.out.println("OUT: " + out + "  -> SAME: " + deepEquals(new byte[] {0x00, 0x42}, out.value));

    }

**Comment by christophstrobl** [comment] 2021-06-21 08:18
Thanks for the feedback.
I gave the test a try with current spring-data maintenance branches, and I did not see a change in behavior between the versions in that regard.
Since binary data is considered a MongoDB native type (which means on write no type hint is added for it) no conversion will happen if the domain type does not infer a certain target type.
In the test above `Object` is used for the `value` property. So, whatever the MongoDB driver returns for the field will be used.
Things look different for a typed domain object (like below). In that case we can identify the target type and convert the result accordingly.

```java
public static class TypedDomainObject extends TestDomainObject<byte[]> {}
// ...
TestDomainObject<?> out = template.findOne(query, TypedDomainObject.class, "exampleCollection");
```

Maybe I'm missing something here, in that case please provide a sample GH project with all required dependencies, and we'll be happy to have another look.

**Comment by spring-projects-issues** [comment] 2021-06-28 08:22
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-projects-issues** [comment] 2021-07-05 08:22
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Comment by gtomassi** [comment] 2021-07-06 16:16
@otasman Could use your help putting together a mini gradle/intellij project or something that replicates the issue so they can replicate it.

**Comment by otasman** [comment] 2021-07-06 18:22
@christophstrobl 
Here is a main and gradle file that easily recreated the issue where all you need to do is change which version of the spring-data-mongodb driver compile is commented out

main
```java
import com.mongodb.ConnectionString;
import com.mongodb.MongoClientSettings;
import com.mongodb.reactivestreams.client.MongoClient;
import com.mongodb.reactivestreams.client.MongoClients;
import org.bson.types.Binary;
import org.springframework.core.convert.converter.Converter;
import org.springframework.data.convert.ReadingConverter;
import org.springframework.data.mongodb.core.ReactiveMongoOperations;
import org.springframework.data.mongodb.core.ReactiveMongoTemplate;
import org.springframework.data.mongodb.core.convert.MappingMongoConverter;
import org.springframework.data.mongodb.core.convert.MongoCustomConversions;
import org.springframework.data.mongodb.core.query.Query;
import org.springframework.data.mongodb.core.query.Update;

import java.util.Collections;
import java.util.List;

import static java.util.Objects.deepEquals;
import static org.springframework.data.mongodb.core.query.Criteria.where;

public class main {

    private static final String connectionString = <CONNECTION STRING>;
    private static final String databaseName = "unitTestDb";

    @ReadingConverter
    public static class BinaryDecoder implements Converter<Binary, Object> {
        @Override
        public byte[] convert(Binary source) {
            return source.getData();
        }
    }

    public static void main(String[] args) {

        MongoClient mongoClient = MongoClients.create(
            MongoClientSettings.builder()
                .applyConnectionString(new ConnectionString(connectionString))
                .build()
        );

        // Build spring operations with custom converters
        ReactiveMongoOperations mongo = new ReactiveMongoTemplate(mongoClient, databaseName);
        MappingMongoConverter converter = (MappingMongoConverter) mongo.getConverter();
        List<?> customConversions = Collections.singletonList(new BinaryDecoder());
        converter.setCustomConversions(new MongoCustomConversions(customConversions));
        converter.afterPropertiesSet();


        Query query = new Query(where("foo").is("bar"));
        mongo.upsert(query, new Update().set("value", new byte[] {0x00, 0x42}), "exampleCollection").block();
        TestDomainObject<?> out = mongo.findOne(query, TestDomainObject.class, "exampleCollection").block();

        System.out.println("OUT: " + out + "  -> SAME: " + deepEquals(new byte[] {0x00, 0x42}, out.value));

        System.exit(0);
    }

    public static class TestDomainObject<V> {

        protected String foo;
        protected V value;

        @Override
        public String toString() {
            return "TestDomainObject{" +
                    "foo='" + foo + '\'' +
                    ", value=" + value +
                    '}';
        }
    }
}

```

build.gradle
```
plugins {
    id 'java'
}

group 'com.jooni'
version '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {

    compile 'io.projectreactor:reactor-core:3.4.7'
    compile 'org.mongodb:mongodb-driver-reactivestreams:4.2.3'

    compile 'org.springframework.data:spring-data-mongodb:3.1.7'
    // compile 'org.springframework.data:spring-data-mongodb:3.2.2'

}

```

**Comment by gtomassi** [comment] 2021-07-09 17:47
@christophstrobl @spring-projects-issues 
Can you please reopen now that we've provided an example project with dependencies?

**Comment by christophstrobl** [comment] 2021-07-12 08:46
@otasman thanks for the sample. I see the custom `Converter` had been the missing bit.
Good catch - we'll take care of that.

**Closed** 2021-07-15 07:00 UTC
Labels: type: regression
