### ISSUE TITLE
Big performance overhead querying records

### ISSUE THREAD

**Issue by sebasmoyano** [spring-projects/spring-data-mongodb#3814] opened 2021-09-09 18:01 UTC
I have a mongo collection with `21` records. Querying all the records it takes `123ms` and using the driver directly takes `19ms`. So it is about `6x` slower. 

The version used of Spring Data is `2.1.10.RELEASE`.

This is causing big performance issues in our project.

Any help would be really appreciated.

**Comment by christophstrobl** [comment] 2021-09-10 04:37
The spring data Lovelace release train (which data-mongo 2.1.x is part of) reached EOL in Oct. 2020. Please upgrade to a more recent version.
If the problem still exists with a newer version please spend some time describing it. What do the domain types look like, how do you retrieve data,... 
Ideally provide a complete [minimal sample](https://stackoverflow.com/help/minimal-reproducible-example) (something that we can unzip or git clone, build, and deploy) or even a JMH Benchmark that shows the problem.

**Comment by sebasmoyano** [comment] 2021-09-10 12:04
It is very simple to reproduce the issue using a simple test case:

```
@Test
    public void testPerformance() {
        long springDataTestStart = System.currentTimeMillis();
        List<Entity> entities = mongoRepository.find(new Query(), Entity.class, Idea2Collection.ENTITIES.getSystemNamespace(true));
        long springDataTestEnd = System.currentTimeMillis();
        System.out.println("Query took: " + ((springDataTestEnd - springDataTestStart)) + "ms");

        long mongoDriverTestStart = System.currentTimeMillis();
        MongoDbCursor entities2 = mongoRepository.find(Idea2Collection.ENTITIES.getSystemNamespace(true));
        List<Document> rawEntities = new ArrayList<>();
        while (entities2.hasNext()) {
            Document document = entities2.next();
            rawEntities.add(document);
        }
        long mongoDriverTestEnd = System.currentTimeMillis();
        System.out.println("Query took: " + ((mongoDriverTestEnd - mongoDriverTestStart)) + "ms");
    }
```

The output is:
```
Query took: 145ms
Query took: 13ms
```

Find attached an example of the documents that we are reading from database.
[entity.zip](https://github.com/spring-projects/spring-data-mongodb/files/7143588/entity.zip)

**Comment by sebasmoyano** [comment] 2021-09-10 12:23
> The spring data Lovelace release train (which data-mongo 2.1.x is part of) reached EOL in Oct. 2020. Please upgrade to a more recent version.
> If the problem still exists with a newer version please spend some time describing it. What do the domain types look like, how do you retrieve data,...
> Ideally provide a complete [minimal sample](https://stackoverflow.com/help/minimal-reproducible-example) (something that we can unzip or git clone, build, and deploy) or even a JMH Benchmark that shows the problem.

I got same results by using version `2.1.21.RELEASE`.

**Comment by mp911de** [comment] 2021-09-13 13:53
A single test isn't sufficient for benchmarking as running all Spring Data code once includes warmup (reflective analysis of the domain model, cache warming, interpreted code paths). These things happen typically once for the entire application runtime, yet your test includes these times in your measurement. 

Please make sure to properly warm up and allow for JIT compilation that you can ideally achieve by using JMH.

**Comment by spring-projects-issues** [comment] 2021-09-20 13:57
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-projects-issues** [comment] 2021-09-27 13:58
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-projects-issues** 2021-09-27 13:58 UTC
Labels: status: waiting-for-feedback, status: feedback-reminder
