### ISSUE TITLE
Is the matcherType of EXACT wrong ? It is a regular expression not the exact string

### ISSUE THREAD

**Issue by xuyingjie-coder** [spring-projects/spring-data-mongodb#4254] opened 2022-12-18 09:56 UTC
https://github.com/spring-projects/spring-data-mongodb/blob/187f260fe4d868f76f9b2a9b08b01d05fa82f4ab/spring-data-mongodb/src/main/java/org/springframework/data/mongodb/core/query/MongoRegexCreator.java#L84

Thanks

**Comment by mp911de** [comment] 2023-01-09 15:27
If you would like us to spend some time helping you to diagnose the problem, please spend some time describing it and, ideally, providing a [minimal sample](https://stackoverflow.com/help/mcve) that reproduces the problem.

**Comment by spring-projects-issues** [comment] 2023-01-16 15:27
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-projects-issues** [comment] 2023-01-23 15:27
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-projects-issues** 2023-01-23 15:27 UTC
Labels: status: waiting-for-feedback, status: waiting-for-triage, status: feedback-reminder
