### ISSUE TITLE
MappingMongoConverter does not work while convert a field which declared with  Map<String ，Object >

### ISSUE THREAD

**Issue by baobinghai** [spring-projects/spring-data-mongodb#3530] opened 2020-12-31 10:47 UTC
In java , version 11..17.RELEASE :

 A  JSONObject  would be  recognised   as a   Map<String,Object> . 

It  happen to that JSONObject   have a BigDecimal field, so i  register a couple of converts : 
 
   1)  BigDecimalToDecimal128Converter  for WritingConverter
   2)  Decimal128ToBigDecimalConverter   for ReadingConverter

however ,    BigDecimalToDecimal128Converter  for WritingConverter   works,
but              Decimal128ToBigDecimalConverter   for ReadingConverter does not work .

it is cased by 

>
     org.springframework.data.mongodb.core.convert.MappingMongoConverter.getPotentiallyConvertedSimpleRead: 

     if (value == null || target == null || target.isAssignableFrom(value.getClass())) {
			return value;
		}

and I also found that i cannot use a  customer MappingMongoConverter, because  argument **ObjectPath** in method readMap 
cannot not be accessed from outside package:

> 
       MappingMongoConverter converter = new MappingMongoConverter(dbRefResolver, mappingContext) {
            
            @Override
            protected Map<Object, Object> readMap(TypeInformation<?> type, DBObject dbObject, ObjectPath path) {
                return null;
            }
        };

**Comment by christophstrobl** [comment] 2021-01-12 10:32
That's a flaw we need to investigate since the Map value type is object and custom converter is registered no type info is written, so on read we cannot determine the desired target type. Maybe there's a way to tell from the type used by the driver itself.
We need to investigate options here. If you have a solution in mind (and the time to code it) please feel free to open a PR.

**Comment by thekaleidoscope** [comment] 2021-10-18 12:43
@christophstrobl @mp911de is this still relevent? if so, can you please validate my understanding above?

**Comment by thekaleidoscope** [comment] 2021-11-20 13:30
@christophstrobl Hello, can you please let me know if my understanding of the issue is correct and if it's still relevant to work on it?

**Comment by christophstrobl** [comment] 2023-03-10 12:49
Thanks for providing the test and sorry for long silence. We've been revisiting the issue and the mapping behaves as expected within its boundaries for resolving generic signatures. Since we do not have any data point for resolving the generic type of `content` in the given example we cannot determine which value to map it to. The writing `Converter` in turn must not know about the context it is called in. 
There's actually a couple of ways how to address the issue ranging from a more strongly typed model over, a custom `Converter` that would add type information, to a property specific `ValueConverter`.

**Comment by baobinghai** [comment] 2023-03-10 12:49
这是来自QQ邮箱的自动回复邮件。
 
您好，我尽快给您回复。

**Closed by christophstrobl** 2023-03-10 12:49 UTC
Labels: status: ideal-for-contribution, in: mapping
